import type { ModelArtifactDto, ModelDto, ModelMetricDto, ModelVersionDto, ModelVersionStage } from "@mlops/contracts";
import { AppIcon, Button, DelayedLoadingState, ErrorState, Notice, SelectField } from "@mlops/ui";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { isModelNotFound, isVersionNotFound, modelsApi } from "../api";
import { ModelStageBadge } from "../components/ModelStageBadge";
import { formatBytes, formatDate, stageOptions } from "../modelViewModel";
import { ModelNotFoundPage } from "./ModelNotFoundPage";

export function ModelVersionPage() {
  const { modelId = "", versionId = "" } = useParams(); const [model, setModel] = useState<ModelDto | null>(null); const [version, setVersion] = useState<ModelVersionDto | null>(null); const [metrics, setMetrics] = useState<ModelMetricDto[]>([]); const [artifacts, setArtifacts] = useState<ModelArtifactDto[]>([]); const [stage, setStage] = useState<ModelVersionStage>("staging"); const [state, setState] = useState<"loading" | "ready" | "error" | "model-not-found" | "version-not-found">("loading"); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [saveError, setSaveError] = useState(""); const [reloadKey, setReloadKey] = useState(0);
  useEffect(() => { let active = true; setState("loading"); Promise.all([modelsApi.getModel(modelId), modelsApi.getVersion(modelId, versionId), modelsApi.getVersionMetrics(modelId, versionId), modelsApi.getVersionArtifacts(modelId, versionId)]).then(([modelData, versionData, metricData, artifactData]) => { if (active) { setModel(modelData); setVersion(versionData); setStage(versionData.stage); setMetrics(metricData); setArtifacts(artifactData); setState("ready"); } }).catch((error) => { if (!active) return; if (isModelNotFound(error)) setState("model-not-found"); else if (isVersionNotFound(error)) setState("version-not-found"); else setState("error"); }); return () => { active = false; }; }, [modelId, versionId, reloadKey]);
  const saveStage = async () => { if (!version) return; setSaving(true); setSaveError(""); try { const updated = await modelsApi.updateVersionStage(modelId, versionId, { stage }); setVersion(updated); setNotice("Стадия версии обновлена."); } catch { setSaveError("Не удалось обновить стадию."); } finally { setSaving(false); } };
  if (state === "loading") return <DelayedLoadingState loading label="Загружаем версию модели…" />;
  if (state === "model-not-found") return <ModelNotFoundPage kind="model" />;
  if (state === "version-not-found") return <ModelNotFoundPage kind="version" />;
  if (state === "error") return <ErrorState title="Не удалось загрузить версию" description="Проверьте подключение к API и попробуйте снова." onRetry={() => setReloadKey((value) => value + 1)} />;
  if (!model || !version) return null;
  return <section className="models-page model-version-page">{notice ? <Notice>{notice}</Notice> : null}{saveError ? <Notice tone="error">{saveError}</Notice> : null}<div className="model-version-heading"><Link className="model-back" to={`/models/${model.id}`} aria-label="К истории версий"><AppIcon name="arrowLeft" size={20} aria-hidden /></Link><div><span className="version-eyebrow">{model.name}</span><div className="version-title-line"><h1>{version.version}</h1><ModelStageBadge stage={version.stage} /></div><p>{version.description}</p></div></div>
    <div className="version-overview-grid"><div className="version-overview-card"><span><AppIcon name="gauge" size={21} aria-hidden /></span><small>Задержка (p95)</small><strong>{version.latencyP95Ms === null ? "Нет данных" : `${version.latencyP95Ms}ms`}</strong></div><div className="version-overview-card"><span><AppIcon name="calendar" size={21} aria-hidden /></span><small>Автор / Дата</small><strong>{version.author}</strong><em>{formatDate(version.createdAt)}</em></div><div className="version-stage-card"><SelectField label="Стадия версии" value={stage} onChange={(event) => setStage(event.currentTarget.value as ModelVersionStage)} disabled={saving}>{stageOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</SelectField><Button type="button" onClick={saveStage} disabled={saving || stage === version.stage}>{saving ? "Сохранение…" : "Сохранить стадию"}</Button></div></div>
    <div className="version-content-grid"><div className="version-data-card"><div className="version-data-card__title"><AppIcon name="gauge" size={20} aria-hidden /><h2>Метрики качества</h2><Link to={`/experiments?modelId=${encodeURIComponent(model.id)}&versionId=${encodeURIComponent(version.id)}`}>Эксперименты</Link></div>{metrics.length ? <div className="metric-list">{metrics.map((metric) => <div key={metric.key}><span>{metric.label}</span><strong>{metric.formattedValue}</strong></div>)}</div> : <p className="version-data-empty">Метрики для этой версии не зарегистрированы</p>}</div><div className="version-data-card"><div className="version-data-card__title"><AppIcon name="file" size={20} aria-hidden /><h2>Артефакты</h2><Link to={`/datasets?modelId=${encodeURIComponent(model.id)}`}>Данные</Link></div>{artifacts.length ? <div className="artifact-list">{artifacts.map((artifact) => <div key={artifact.id}><span className="artifact-icon"><AppIcon name="file" size={17} aria-hidden /></span><span><strong>{artifact.name}</strong><small>{artifact.type} • {formatBytes(artifact.sizeBytes)}</small></span></div>)}</div> : <p className="version-data-empty">Артефакты отсутствуют</p>}</div></div><div className="version-related-link"><Link to={`/deployments?modelId=${encodeURIComponent(model.id)}&versionId=${encodeURIComponent(version.id)}`}>Перейти к развёртываниям этой версии</Link></div>
  </section>;
}
